### ISSUE TITLE
Provide precompiled binaries for Download

### ISSUE THREAD

**Issue by 0x46616c6b** [mguentner/mumble_exporter#5]
Hey, 

I stumbled over this exporter and used them now. But I not using NixOS and would like to have the option to download compiled binaries from the exporter. For this I used in the past GitHub Releases together with a Changelog to provide downloadable binaries. Would you be open for that? I could create a PR with this feature (GitHub Actions).

WDYT?

**Comment by mguentner** [comment]
Sounds good, feel free to contribute a PR.

**Comment by mguentner** [comment]
closed with 43b9d7f4fe6227d74ba5178407a31a8affdc3656
